SinusoidalWall Class Reference
Public Member Functions
SinusoidalWall (const double &height, const double &amplitude, const double &zeta_min, const double &zeta_max)
Constructor: Pass height, amplitude, zeta min and zeta max (all are pinned by default)
SinusoidalWall (const Vector< Data * > &geom_data_pt)
Constructor: One item of geometric data, containing four values:
~SinusoidalWall ()
Destructor: Clean up if necessary.
double & height ()
Access function for horizontal half axis.
double & amplitude ()
Access function for vertical half axis.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep.
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
Derivative of position Vector w.r.t. to coordinates: $ \frac{dR_i}{d \zeta_\alpha}$ = drdzeta(alpha,i). Evaluated at current time.
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
2nd derivative of position Vector w.r.t. to coordinates: $ \frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}$ = ddrdzeta(alpha,beta,i). Evaluated at current time.
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Posn Vector and its 1st & 2nd derivatives w.r.t. to coordinates: $ \frac{dR_i}{d \zeta_\alpha}$ = drdzeta(alpha,i). $ \frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}$ = ddrdzeta(alpha,beta,i). Evaluated at current time.
unsigned ngeom_data () const
How many items of Data does the shape of the object depend on?
Data * geom_data_pt (const unsigned &j)
Return pointer to the j-th Data item that the object's shape depends on
Private Attributes
Vector< Data * > Geom_data_pt
Vector of pointers to Data items that affects the object's shape.
bool Must_clean_up
Do I need to clean up?
Detailed Description
Geometric object representing a sinusoidal wall, parametrised by
 x = \zeta 
 y = H + A \sin\left(\frac{2\pi \left(\zeta-\zeta_{\mbox{min}}\right)} {\zeta_{\mbox{max}}-\zeta_{\mbox{min}}} \right)
Definition at line 72 of file spine_channel.cc.
Constructor & Destructor Documentation
SinusoidalWall() [1/2]
SinusoidalWall::SinusoidalWall (const double & height, const double & amplitude, const double & zeta_min, const double & zeta_max) [inline]
Constructor: Pass height, amplitude, zeta min and zeta max (all are pinned by default)
Definition at line 79 of file spine_channel.cc.
References amplitude(), Geom_data_pt, height(), and Must_clean_up.
SinusoidalWall() [2/2]
SinusoidalWall::SinusoidalWall (const Vector< Data * > & geom_data_pt) [inline]
Constructor: One item of geometric data, containing four values:
Geom_data_pt[0]->value(0) = height
Geom_data_pt[0]->value(1) = amplitude
Geom_data_pt[0]->value(2) = zeta_min
Geom_data_pt[0]->value(3) = zeta_max
Definition at line 111 of file spine_channel.cc.
References geom_data_pt(), Geom_data_pt, and Must_clean_up.
 SinusoidalWall()
SinusoidalWall::~SinusoidalWall () [inline]
Destructor: Clean up if necessary.
Definition at line 140 of file spine_channel.cc.
References Geom_data_pt, and Must_clean_up.
Member Function Documentation
amplitude()
double & SinusoidalWall::amplitude () [inline]
Access function for vertical half axis.
Definition at line 154 of file spine_channel.cc.
References Geom_data_pt.
Referenced by SinusoidalWall().
d2position() [1/2]
virtual void SinusoidalWall::d2position (const Vector< double > & zeta, RankThreeTensor< double > & ddrdzeta) const [inline], [virtual]
2nd derivative of position Vector w.r.t. to coordinates: $ \frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}$ = ddrdzeta(alpha,beta,i). Evaluated at current time.
Definition at line 237 of file spine_channel.cc.
References Global_Physical_Variables::A, and Geom_data_pt.
d2position() [2/2]
virtual void SinusoidalWall::d2position (const Vector< double > & zeta, Vector< double > & r, DenseMatrix< double > & drdzeta, RankThreeTensor< double > & ddrdzeta) const [inline], [virtual]
Posn Vector and its 1st & 2nd derivatives w.r.t. to coordinates: $ \frac{dR_i}{d \zeta_\alpha}$ = drdzeta(alpha,i). $ \frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}$ = ddrdzeta(alpha,beta,i). Evaluated at current time.
Definition at line 258 of file spine_channel.cc.
References Global_Physical_Variables::A, Geom_data_pt, and Global_Physical_Variables::H.
dposition()
virtual void SinusoidalWall::dposition (const Vector< double > & zeta, DenseMatrix< double > & drdzeta) const [inline], [virtual]
Derivative of position Vector w.r.t. to coordinates: $ \frac{dR_i}{d \zeta_\alpha}$ = drdzeta(alpha,i). Evaluated at current time.
Definition at line 218 of file spine_channel.cc.
References Global_Physical_Variables::A, and Geom_data_pt.
geom_data_pt()
Data * SinusoidalWall::geom_data_pt (const unsigned & j) [inline]
Return pointer to the j-th Data item that the object's shape depends on
Definition at line 289 of file spine_channel.cc.
References Geom_data_pt.
Referenced by SinusoidalWall().
height()
double & SinusoidalWall::height () [inline]
Access function for horizontal half axis.
Definition at line 151 of file spine_channel.cc.
References Geom_data_pt.
Referenced by SinusoidalWall().
ngeom_data()
unsigned SinusoidalWall::ngeom_data () const [inline]
How many items of Data does the shape of the object depend on?
Definition at line 285 of file spine_channel.cc.
References Geom_data_pt.
position() [1/2]
void SinusoidalWall::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const [inline]
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep.
Definition at line 184 of file spine_channel.cc.
References Global_Physical_Variables::A, Geom_data_pt, and Global_Physical_Variables::H.
position() [2/2]
void SinusoidalWall::position (const Vector< double > & zeta, Vector< double > & r) const [inline]
Position vector at Lagrangian coordinate zeta.
Definition at line 158 of file spine_channel.cc.
References Global_Physical_Variables::A, Geom_data_pt, and Global_Physical_Variables::H.
Member Data Documentation
Geom_data_pt
Vector<Data*> SinusoidalWall::Geom_data_pt [private]
Vector of pointers to Data items that affects the object's shape.
Definition at line 295 of file spine_channel.cc.
Referenced by amplitude(), d2position(), dposition(), geom_data_pt(), height(), ngeom_data(), position(), SinusoidalWall(), and ~SinusoidalWall().
Must_clean_up
bool SinusoidalWall::Must_clean_up [private]
Do I need to clean up?
Definition at line 298 of file spine_channel.cc.
Referenced by SinusoidalWall(), and ~SinusoidalWall().
The documentation for this class was generated from the following file:
spine_channel.cc