name: Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      publishBranch:
        description: "Branch to publish built docs"
        required: true
        default: "gh-pages"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install requirements (minus doxygen)
        run: sudo apt-get install cmake doxygen gawk ninja-build make automake libtool libtool-bin autoconf gfortran g++ texlive texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra texlive-font-utils

      # FIXME: Relies on doxygen.nl being alive
      - name: Bleeding edge doxygen
        run: |
          wget https://www.doxygen.nl/files/doxygen-1.9.6.linux.bin.tar.gz
          tar xvfz doxygen-1.9.6.linux.bin.tar.gz
          sudo apt install libclang1-12
          sudo apt install libclang-cpp12
          echo "new doxygen (as installed):"
          doxygen-1.9.6/bin/doxygen --version
          sudo mv doxygen-1.9.6/bin/doxygen /usr/bin/doxygen
          echo "new doxygen (installed in /usr/bin):"
          which doxygen
          doxygen --version

      - name: Build doc
        run: |
          cmake -G Ninja -S doc/ -B doc/build
          cmake --build doc/build
          rm -rf doc/build

      - name: Run website install script
        run: ./scripts/website_install.sh

      - name: Grab redirect file
        run: cp ./scripts/redirect.html ./build/website/index.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: "gh-pages-cmake" # The branch the action should deploy to.
          FOLDER: build/website # The folder the action should deploy.
          CLEAN: true
