name: Formatting

on:
  # Trigger the workflow when a push is made to any branch except 'main'. The
  # intention here is that this workflow should be triggered in the following
  # cases:
  #  1. When a pull request has been merged in to 'development'; a push event
  #     will be created for the 'development' branch, so the workflow will be
  #     triggered and run then.
  #  2. When the user pushes changes to any branch in their own forked
  #     repository except 'main' and 'development', as these branches should
  #     never be edited directly by a user.
  push:
    branches-ignore:
      - main
    paths:
      # We only need to run this workflow if we edited the sources
      - ".github/workflows/cmake-and-clang-format.yaml"
      - "*.cmake"
      - "CMakeLists.txt"
      - "src/**.h"
      - "src/**.cc"
      - "src/**.tpp"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Format all files in the src/ directory except cfortran.h, lapack_qz.h,
      # superlu.c, superlu_dist.c, which sit in the src/generic/ subdirectory.
      - name: Format oomph-lib sources
        uses: puneetmatharu/clang-format-lint-action@v0.17
        with:
          files: ^(src)\/(?!.*(cfortran|lapack_qz))(.+)\.(h|hpp|cc|cpp|tpp)$
          clangFormatVersion: 16.0.3
          style: file
          inplace: True

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: clang-format-bot
          commit_message: "Automated commit of clang-format CI changes."

      - name: Format CMake files
        id: cmake-format
        uses: puneetmatharu/cmake-format-lint-action@v1.0.0
        with:
          args: --config-files .cmake-format.py --in-place

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: cmake-format-bot
          commit_message: "Automated commit of cmake-format CI changes."
