name: Code coverage

on: push

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  COVERAGE_REPORT_NAME: 'coverage-report.html'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        OOMPH_USE_OPENBLAS: ["ON"]

    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: brew install cmake open-mpi ninja openblas gcovr fd && brew reinstall gfortran

      - name: Configure, build & install
        run: cmake --preset CI-build-with-coverage -B build && cd build && ninja
        env:
          OOMPH_USE_OPENBLAS: ${{ matrix.OOMPH_USE_OPENBLAS }}

      - name: Run self-tests
        id: self_tests
        run: |
          cd demo_drivers && cp ../CMakePresets.json ./
          cmake --preset CI-demo-drivers-with-coverage
          cd build && cp ../CMakePresets.json ./
          ctest --preset CI-demo-drivers-with-coverage -j $(sysctl -n hw.logicalcpu)
        continue-on-error: true
        env:
          OOMPH_BUILD_PATH: '${{ github.workspace }}/build'

      - name: Generate code coverage report
        run: |
          fd .gcno build/external_{src,distributions} -x rm -f {}
          mkdir coverage_reports
          gcovr -r . --html --html-details -o coverage_reports/${{ env.COVERAGE_REPORT_NAME }}

      - name: Upload code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report-${{ runner.os }}.html
          path: ./coverage_reports/

      - name: Propagate CTest status
        if: steps.self_tests.outcome == 'failure'
        run: exit 8
