name: CMake build & self-test

on:
  push:
    branches:
      - feature/convert-to-cmake-build-system

env:
  CMAKE_BUILD_TYPE: Debug
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-18.04
            compiler: gcc
            install-deps: |
              sudo apt-get install -y gfortran openmpi-bin

          - os: ubuntu-latest
            compiler: gcc
            install-deps: |
              sudo apt-get install -y gfortran openmpi-bin

          - os: macos-latest
            compiler: clang
            install-deps: |
              brew install cmake open-mpi
              brew reinstall gfortran

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install dependencies
        run: ${{ matrix.install-deps }}

      - name: Install CMake (Linux)
        if: runner.os == 'Linux'
        run: |
          ${{ matrix.install-deps }}
          curl -sSL https://github.com/Kitware/CMake/releases/download/v3.16.0/cmake-3.16.0-Linux-x86_64.tar.gz -o cmake.tar.gz
          sudo tar xf cmake.tar.gz --strip 1 -C /usr/local

      - name: Output CMake version
        run: cmake --version

      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure (${{ env.CMAKE_BUILD_TYPE }})
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} ..

      - name: Build & install
        working-directory: build
        run: |
          make --jobs 10
          make install

      # - name: Run self-tests
      #   run: |
      #     cd demo_drivers
      #     mkdir build && cd build
      #     cmake -G Ninja ..
      #     ctest -C ${{ env.CMAKE_BUILD_TYPE }}