--- # ------------------------------------------------------------------------------
name: macOS

on: push

# Environment variable(s) that can be read during jobs
env:
  # The oomph-lib installation location
  OOMPH_INSTALL_PATH: "${{ github.workspace }}/.local"
  CC: clang
  CXX: clang++

# ------------------------------------------------------------------------------

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # NOTE: The main options are: [
        #   {status: "OFF", preset: CI-build},
        #   {status: "ON",  preset: CI-mpi-build}
        # ]
        mpi_info: [{ status: "OFF", cmake_preset: CI-build }]

    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: brew install cmake ninja openblas fd && brew reinstall gcc

      - name: Install MPI dependencies (if required)
        if: matrix.mpi_info.status == 'ON'
        run: brew install open-mpi

      - name: Configure, build & install
        run: |
          cmake --preset ${{ matrix.mpi_info.cmake_preset }} \
          -D CMAKE_PREFIX_PATH="/usr/local/Cellar/openblas/0.3.21" \
          -D CMAKE_INSTALL_PREFIX='${{ env.OOMPH_INSTALL_PATH }}' \
          -D OOMPH_ENABLE_USE_OPENBLAS=ON \
          -B build && cd build && ninja && ninja install

      - name: Run self-tests
        id: self_tests
        run: |
          cd demo_drivers && cp ../CMakePresets.json ./
          cmake --preset CI-demo-drivers -D CMAKE_PREFIX_PATH='${{ env.OOMPH_INSTALL_PATH }}' -B build
          cd build && cp ../CMakePresets.json ./
          ctest --preset CI-demo-drivers -j $(sysctl -n hw.logicalcpu)
        continue-on-error: true

      - name: Upload validation log file
        uses: actions/upload-artifact@v2
        with:
          name: validation-${{ runner.os }}-MPI_${{ matrix.mpi_info.status }}.log
          path: ./validation.log

      - name: Propagate CTest status
        if: steps.self_tests.outcome == 'failure'
        run: exit 8
# ------------------------------------------------------------------------------
