--- # ------------------------------------------------------------------------------
name: macOS

# TODO: Possibly add on-push-paths triggers below to only trigger self-tests when .c, .h, .cc,
# .cmake, .py, .sh, CMakeLists.txt and workflow files are pushed
on: push

# Environment variables that can be read during jobs
env:
  CTEST_OUTPUT_ON_FAILURE: 1
  OOMPH_INSTALL_PATH: "${{ github.workspace }}/.local"

# ------------------------------------------------------------------------------

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build_info:
          [{ mpi_status: "OFF", cmake_preset: CI-build }]
          # { mpi_status: "ON", cmake_preset: CI-mpi-build },

    runs-on: macos-12
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install cmake ninja openblas fd && brew reinstall gcc

      - name: Install MPI dependencies (if required)
        if: matrix.build_info.mpi_status == 'ON'
        run: brew install open-mpi

      - name: Configure
        run: cmake -DOOMPH_BUILD_DEMO_DRIVERS_WITH_LIBRARY=ON --preset ${{ matrix.build_info.cmake_preset }} --install-prefix ${{ env.OOMPH_INSTALL_PATH }} -B build
        env:
          # Where to look to find the Homebrew-installed OpenBLAS libraries
          CMAKE_PREFIX_PATH: "/usr/local/Cellar/openblas/0.3.21"

      - name: Build
        run: cd build && ninja -v elastic_bretherton

      - name: Run self-tests
        id: self_tests
        run: |
          OOMPH_MAIN_DIR=$(pwd)
          cd build
          ctest -R interaction.elastic_bretherton
          cd demo_drivers/interaction/elastic_bretherton/
          for i in $(seq 1 10); do
            ./validate.sh "${OOMPH_MAIN_DIR}";
          done
        continue-on-error: true

      - name: Upload validation log file
        uses: actions/upload-artifact@v3
        with:
          name: validation-${{ runner.os }}-MPI_${{ matrix.build_info.mpi_status }}.log
          path: ./validation.log

      - name: Propagate CTest mpi_status
        if: steps.self_tests.outcome == 'failure'
        run: exit 8
# ------------------------------------------------------------------------------
