--- # ------------------------------------------------------------------------------
name: macOS

# TODO: Possibly add on-push-paths triggers below to only trigger self-tests when .c, .h, .cc,
# .cmake, .py, .sh, CMakeLists.txt and workflow files are pushed
on: push

# Environment variables that can be read during jobs
env:
  CTEST_OUTPUT_ON_FAILURE: 1

# ------------------------------------------------------------------------------

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build_info: [{ mpi: "OFF", preset: ci }, { mpi: "ON", preset: ci-mpi }]

    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install cmake ninja openblas fd gmp mpfr boost && brew reinstall gcc

      - name: Install MPI dependencies (if required)
        if: matrix.build_info.mpi == 'ON'
        run: brew install open-mpi

      - name: Configure
        run: cmake --preset ${{ matrix.build_info.preset }} -DCMAKE_PREFIX_PATH=$(brew --prefix openblas) -B build

      - name: Build
        run: cmake --build build

      - name: Install
        run: cmake --install build

      - name: Configure basic self-tests
        run: cmake -G Ninja -S self_test -B self_test/build --log-level=VERBOSE -DOOMPH_WANT_EXTENDED_SELF_TESTS=ON

      - name: Run basic self-tests
        id: self_tests
        run: ctest --preset ci --test-dir self_test/build -j $(sysctl -n hw.logicalcpu)
        continue-on-error: true

      - name: Configure demo drivers
        run: cmake -G Ninja -S demo_drivers -B demo_drivers/build --log-level=VERBOSE

      - name: Run demo driver self-tests
        id: demo_drivers
        run: ctest --preset ci --test-dir demo_drivers/build -j $(sysctl -n hw.logicalcpu)
        continue-on-error: true

      - name: Upload validation log file
        uses: actions/upload-artifact@v3
        with:
          name: validation-${{ runner.os }}-MPI_${{ matrix.build_info.mpi }}.log
          path: ./validation.log

      - name: Propagate CTest test status
        if: steps.self_tests.outcome == 'failure' || steps.demo_drivers.outcome == 'failure'
        run: exit 8
# ------------------------------------------------------------------------------
