--- # ------------------------------------------------------------------------------
name: Ubuntu

# TODO: Possibly add on-push-paths triggers below to only trigger self-tests when .c, .h, .cc,
# .cmake, .py, .sh, CMakeLists.txt and workflow files are pushed
on: push

# Environment variables that can be read during jobs
env:
  CTEST_OUTPUT_ON_FAILURE: 1
  OOMPH_INSTALL_PATH: "${{ github.workspace }}/.local"

# ------------------------------------------------------------------------------

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # NOTE: The main options are: [
        #   {status: "OFF", preset: CI-build},
        #   {status: "ON",  preset: CI-mpi-build}]
        build_info: [{ status: "OFF", cmake_preset: CI-build }]

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y gfortran ninja-build libopenblas-dev

      - name: Install MPI dependencies (if required)
        if: matrix.build_info.status == 'ON'
        run: sudo apt-get install openmpi-bin libopenmpi-dev

      - name: Configure
        run: cmake --preset ${{ matrix.build_info.cmake_preset }} --install-prefix ${{ env.OOMPH_INSTALL_PATH }} -B build

      - name: Build
        run: cmake --build build

      - name: Install
        run: cmake --install build

      - name: Configure self-tests
        run: cmake -S demo_drivers -B demo_drivers/build
        env:
          # Tell the demo drivers where to find the installed oomph-lib library
          CMAKE_PREFIX_PATH: ${{ env.OOMPH_INSTALL_PATH }}

      - name: Run self-tests
        id: self_tests
        run: ctest --test-dir demo_drivers/build -j $(nproc)
        continue-on-error: true

      - name: Upload validation log file
        uses: actions/upload-artifact@v2
        with:
          name: validation-${{ runner.os }}-MPI_${{ matrix.build_info.status }}.log
          path: ./validation.log

      - name: Propagate CTest status
        if: steps.self_tests.outcome == 'failure'
        run: exit 8
# ------------------------------------------------------------------------------
