name: Ubuntu

on: push

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  OOMPH_INSTALL_PATH: '${{ github.workspace }}/.local'
  OOMPH_ENABLE_MPI: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y gfortran openmpi-bin libopenmpi-dev ninja-build

      - name: Configure, build & install
        run: cmake --preset CI-build -B build && cd build && ninja && ninja install

      - name: Run self-tests
        id: self_tests
        run: |
          cd demo_drivers && cp ../CMakePresets.json ./
          cmake --preset CI-demo-drivers
          cd build && cp ../CMakePresets.json ./
          ctest --preset CI-demo-drivers -j $(nproc)
        continue-on-error: true

      - name: Upload validation log file
        uses: actions/upload-artifact@v2
        with:
          name: validation-${{ runner.os }}-MPI_${{ env.OOMPH_ENABLE_MPI }}.log
          path: ./validation.log

      - name: Propagate CTest status
        if: steps.self_tests.outcome == 'failure'
        run: exit 8
