name: MacOS

on:
  push:
    branches:
      - feature/convert-to-cmake-build-system

env:
  CMAKE_BUILD_TYPE: Debug
  CTEST_OUTPUT_ON_FAILURE: 1
  INSTALL_LOCATION: .local

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        OOMPH_ENABLE_MPI: [0]
        include:
          - os: macos-latest
            compiler: clang
            install-deps: |
              brew install cmake open-mpi
              brew reinstall gfortran

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install dependencies
        run: ${{ matrix.install-deps }}

      - name: Output CMake version
        run: cmake --version

      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure (${{ env.CMAKE_BUILD_TYPE }})
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} \
          -DOOMPH_ENABLE_MPI=${{ matrix.OOMPH_ENABLE_MPI }} \
          -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/$INSTALL_LOCATION \
          -B build

      - name: Build & install
        working-directory: build
        run: |
          make --jobs 16
          make install

      - name: Run self-tests
        id: self_tests
        run: |
          cd demo_drivers
          cmake -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/$INSTALL_LOCATION -B build
          cd build
          ctest -C ${{ env.CMAKE_BUILD_TYPE }} -j 8 --timeout 10000
        continue-on-error: true

      - name: Get failed test info.
        if: steps.self_tests.outcome == 'failure'
        run: |
          ctest -C ${{ env.CMAKE_BUILD_TYPE }} -j 8 --timeout 10000 --rerun-failed --output-on-failure
