name: Ubuntu

on: push

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        OOMPH_ENABLE_MPI: ["OFF"]
        OOMPH_USE_OPENBLAS: ["ON"]
        OOMPH_WANT_MUMPS: ["OFF"]

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y gfortran openmpi-bin libopenmpi-dev ninja-build libopenblas-dev

      - name: Configure, build & install
        run: cmake --preset CI-build -B build && cd build && ninja && ninja install
        env:
          OOMPH_USE_OPENBLAS: ${{ matrix.OOMPH_USE_OPENBLAS }}
          OOMPH_ENABLE_MPI: ${{ matrix.OOMPH_ENABLE_MPI }}
          OOMPH_WANT_MUMPS: ${{ matrix.OOMPH_WANT_MUMPS }}
          OOMPH_INSTALL_PATH: '${{ github.workspace }}/.local'

      - name: Run self-tests
        id: self_tests
        run: |
          cd demo_drivers && cp ../CMakePresets.json ./
          cmake --preset CI-demo-drivers
          cd build && cp ../CMakePresets.json ./
          ctest --preset CI-demo-drivers -j $(nproc)
        continue-on-error: true
        env:
          OOMPH_INSTALL_PATH: '${{ github.workspace }}/.local'

      - name: Upload validation log file
        uses: actions/upload-artifact@v2
        with:
          name: validation-${{ runner.os }}-MPI_${{ env.OOMPH_ENABLE_MPI }}-MUMPS_${{ env.OOMPH_WANT_MUMPS }}-OpenBLAS_${{ env.OOMPH_USE_OPENBLAS }}.log
          path: ./validation.log

      - name: Propagate CTest status
        if: steps.self_tests.outcome == 'failure'
        run: exit 8
