# ------------------------------------------------------------------------------

name: Test third-party libraries (macOS)

# Test third-party libs building ONLY if we edited code in external_distributions/
on:
  push:
    paths:
      - ".github/workflows/test-third-party-libs-on-macos.yaml"
      - "external_distributions/CMakeLists.txt"
      - "external_distributions/cmake/**"

# ------------------------------------------------------------------------------

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        mpi: ["OFF", "ON"]

    runs-on: macos-latest
    steps:
      - name: Set output artifact name
        run: echo "TPL_BUILD_LOGS=tpl_build_logs-${{ runner.os }}-MPI_${{ matrix.build_info.enable_mpi }}" >> "$GITHUB_ENV"

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install ninja automake openblas && brew reinstall gcc

      - name: Install MPI dependencies (if required)
        if: matrix.mpi == 'ON'
        run: brew install open-mpi

      - name: Get CMake v3.24
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.24.0"

      - name: Check CMake version
        run: cmake --version

      - name: Configure
        run: |
          cmake -G Ninja \
          -DOOMPH_ENABLE_MPI=${{ matrix.mpi }} \
          -DOOMPH_USE_OPENBLAS_FROM=$(brew --prefix openblas) \
          -DOOMPH_BUILD_MUMPS=OFF \
          -DOOMPH_BUILD_SUPERLU=OFF \
          -DOOMPH_BUILD_SUPERLU_DIST=OFF \
          -DOOMPH_BUILD_CGAL=OFF \
          -DOOMPH_BUILD_HYPRE=OFF \
          -DOOMPH_BUILD_TRILINOS=ON \
          -B build
        working-directory: ./external_distributions/

      - name: Build/install
        id: build
        run: cmake --build build
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        working-directory: ./external_distributions/
        continue-on-error: true

      - name: Rename build logs
        run: mv ./external_distributions/build/logs ./${TPL_BUILD_LOGS}

      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: ${TPL_BUILD_LOGS}
          path: ./${TPL_BUILD_LOGS}

      - name: Propagate build status
        if: steps.build.outcome == 'failure'
        run: exit 1
# ------------------------------------------------------------------------------
