name: macOS

on: push

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        OOMPH_ENABLE_MPI: [true, false]
        OOMPH_WANT_TRILINOS: [true, false]

    runs-on: macos-latest
    steps:
      - env:
          OOMPH_ENABLE_MPI: ${{ matrix.OOMPH_ENABLE_MPI }}
          OOMPH_WANT_TRILINOS: ${{ matrix.OOMPH_WANT_TRILINOS }}
          OOMPH_INSTALL_PATH: '${{ github.workspace }}/.local/MPI_${{ OOMPH_ENABLE_MPI }}-Trilinos_${{ OOMPH_WANT_TRILINOS }}'

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: brew install cmake open-mpi ninja && brew reinstall gfortran

      - name: Configure, build & install
        run: cmake --preset CI-build -B build && ninja && ninja install

      - name: Run self-tests
        id: self_tests
        run: |
          cd demo_drivers && cp ../CMakePresets.json ./
          cmake --preset CI-demo-drivers
          cd build && cp ../CMakePresets.json ./
          ctest --preset CI-demo-drivers -j $(sysctl -n hw.logicalcpu)
        continue-on-error: true

      - name: Upload validation log file
        uses: actions/upload-artifact@v2
        with:
          name: validation-${{ runner.os }}-MPI_${{ env.OOMPH_ENABLE_MPI }}.log
          path: ./validation.log

      - name: Propagate CTest status
        if: steps.self_tests.outcome == 'failure'
        run: exit 8
