name: macOS

on: push

env:
  # Environment variable that controls if the output should be logged for failed
  # CTest tests
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        OOMPH_USE_OPENBLAS: ["ON"]

    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: brew install cmake open-mpi ninja openblas gcovr && brew reinstall gfortran

      - name: Configure, build & install
        run: cmake --preset CI-build -B build && cd build && ninja && ninja install
        env:
          OOMPH_USE_OPENBLAS: ${{ matrix.OOMPH_USE_OPENBLAS }}
          OOMPH_INSTALL_PATH: '${{ github.workspace }}/.local'

      - name: Run self-tests
        id: self_tests
        run: |
          cd demo_drivers && cp ../CMakePresets.json ./
          cmake --preset CI-demo-drivers
          cd build && cp ../CMakePresets.json ./
          ctest --preset CI-demo-drivers -j $(sysctl -n hw.logicalcpu)
        continue-on-error: true
        env:
          OOMPH_INSTALL_PATH: '${{ github.workspace }}/.local'

      - name: Upload validation log file
        uses: actions/upload-artifact@v2
        with:
          name: validation-${{ runner.os }}-OpenBLAS_${{ matrix.OOMPH_USE_OPENBLAS }}.log
          path: ./validation.log

      - name: Propagate CTest status
        if: steps.self_tests.outcome == 'failure'
        run: exit 8
