name: Ubuntu

on: push

env:
  CMAKE_BUILD_TYPE: Release
  CTEST_OUTPUT_ON_FAILURE: 1
  INSTALL_LOCATION: '${{ github.workspace }}/.local'
  OOMPH_ENABLE_MPI: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y gfortran openmpi-bin libopenmpi-dev

      - name: Install Ninja
        run: sudo apt-get install ninja-build

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.16.x'

      # # Should ideally restrict this to 3.17 but doing so leads to the GitHub
      # # Action producing an error as a result of the Action trying to assign
      # # CMake to the path in an "old-fashioned" way. The latest version of this
      # # Action takes care of that.
      # - name: Get latest CMake and Ninja
      #   uses: PuneetMatharu/get-cmake@latest

      - name: Output CMake version
        run: cmake --version

      - name: Configure (${{ env.CMAKE_BUILD_TYPE }})
        run: |
          cmake -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} \
          -DOOMPH_ENABLE_MPI=${{ env.OOMPH_ENABLE_MPI }} \
          -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_LOCATION }} \
          -DOOMPH_ENABLE_PARANOID=OFF \
          -DOOMPH_ENABLE_RANGE_CHECKING=OFF \
          -B build

      - name: Build & install
        working-directory: build
        run: ninja && ninja install

      - name: Run self-tests
        id: self_tests
        run: |
          cd demo_drivers
          cmake -DCMAKE_PREFIX_PATH=${{ env.INSTALL_LOCATION }} -B build
          cd build
          ctest -C ${{ env.CMAKE_BUILD_TYPE }} -j $(nproc) --timeout 10000 --no-label-summary
        continue-on-error: true

      - name: Upload validation log file
        uses: actions/upload-artifact@v2
        with:
          name: validation-${{ runner.os }}-MPI_${{ env.OOMPH_ENABLE_MPI }}.log
          path: ./validation.log

      - name: Propagate status
        if: steps.self_tests.outcome == 'failure'
        run: exit 8
